### ISSUE TITLE
Bad execution order: clients before master & more

### ISSUE THREAD

**Issue by creinig** [rlex/ansible-role-lizardfs#2]
Note: I've only learned to use ansible for the past few days, so I might be very wrong here.

In tasks/main.yml, "include: client.yml" comes before "include: masterserver.yml", causing ansible to try to mount the volumes on the client *before* installing the masterserver. Moving the "include:client.yml" to the end of the file fixes this.
But even then mounting the volumes fails because the "reload lizardfs-masterserver" handler is not executed beforehand, which means that the master is simply not running when we try to mount the volumes.

I'm using ansible 2.6.8.

my hosts.ini:
```
[all]
node1 ansible_host=node1 ip=192.168.100.6
node2 ansible-host=node2 ip=192.168.100.95

[lizardfs-master]
node1 

[lizardfs-shadow]
node2 

[lizardfs-chunkserver]
node1 
node2 

[lizardfs-client]
node1 
node2 

[lizardfs-cluster:children]
lizardfs-master
lizardfs-shadow
lizardfs-chunkserver
lizardfs-client
```

I've placed the configuration into distinct files per role:
```
$ ls -1 inventory/group_vars/ | grep lizard
lizardfs-chunkserver.yml
lizardfs-client.yml
lizardfs-cluster.yml
lizardfs-master.yml
lizardfs-shadow.yml
```

**Comment by creinig** [comment]
Update: the non-execution of the handlers might have been caused because the master configs didn't change from a previous (incomplete) run. I'll investigate that tomorrow.

**Comment by rlex** [comment]
Good catch. I'm wondering how it worked for me, but i installed only two clusters and since they are working i never touched them again. 
Client task should be moved to the end of the execution order for sure.

**Comment by rlex** [comment]
Speaking of non-execution of handler: handlers are run at the end of the role. I will add flush_handlers jobs for each sub-role to ensure they are restarted.

**Comment by rlex** [comment]
I pushed some changes, feel free to test how it works now.

**Comment by creinig** [comment]
Thanks for the quick fix. I've tested it in a VM (CentOS 7) and it works *almost* fine :)

I'm getting "Package: lizardfs-master-3.12.0-0el7.x86_64 (lizardfs)  Requires: libJudy.so.1()" on a blank system, because the EPEL repository is not installed (see https://docs.lizardfs.com/adminguide/installation.html#installing-from-redhat-el-centos-packages). I guess the install.yml should add that as well. Even though most centos admins will add it as one of the first things anyway :)

**Comment by rlex** [comment]
To be honest EPEL is out of scope of this role. Ideally you want separate roles for configuration of every tool, yum included.

**Comment by creinig** [comment]
Fair enough.
